***Rust*** 和其他语言不同的是，将异常分为两大类：**recoverable(可恢复)** 和 **unrecoverable(不可恢复)**。***Rust*** 没有其他语言的 exceptions，作为替代，他有 `Result<T, E>` 类型用来处理 **可恢复类型**；和，`panic!` 宏来中断程序当发生 **不可恢复异常**。


# 使用 `panic!` 处理不可恢复异常
1. 当发生无法处理的异常，***Rust*** 有 `panic!` 宏，当其执行的时候，程序会打印失败信息，**展开 并 清空 栈**，然会退出。我们通常在 当一个某种类型的 bug 被检测到 并且 编写代码时不清楚如何处理这个问题 时 插入一个 panic。
2. 默认，当一个 panic 发生时，程序开始 ***unwinding(展开)***，意味着 ***Rust*** 展开栈并清空它遇见的每个函数中的数据。但是这个动作需要很多工作，因此，***Rust*** 允许选择一个替代性的立即 ***aborting***，结束程序但不清除数据，将这个动作留给操作系统。如果项目需要二进制文件尽可能小，可以通过在 *Cargo.toml* 文件 的 `[profile]` 节 添加 `panic = 'abort';` 例如，如果希望在 release 模式下 panic 的时候 abort，增加：
   ```toml
   [profile.release]
   panic = 'abort'
   ```
3. 使用 `panic!`：`panic!("crash and burn")`。输出：
>thread 'main' panicked at 'crash and burn', src/main.rs:2:5 
>note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
4. 输出中能够看到具体发生 panic 的位置。

## 使用 `panic!` ***Backtrace(回溯)***
1. 在 ***C*** 中，访问超过最大索引的位置，可能会获得无论什么，只要是符合数据结构的那个元素，即使那块内存并不属于那个结构，这被称为 ***buffer overread***，会导致安全脆弱。***Rust*** 编译器不会允许这种操作发生。
2. 一个回溯是一个 为了到达这点的所有被调用函数的 列表。通过设置 `RUST_BACKTRACE=1` 来使异常信息向前追溯，而不局限于此文件。如下：
>$env:RUST_BACKTRACE=1; cargo run // ***Windows 10 powershell***
>RUST_BACKTRACE=1 cargo run // ***Linux*** / ***macOS*** / ***UNIX*** ***bash***
3. 为了获得回溯的输出，debug 符号必须是开启的，在 `cargo build`， `cargo run` 中默认是开启的，除非加了 `--release` 标志。


# 使用 `Result` 处理可恢复异常
大多数错误没有严重到需要完全退出程序，有时当一个函数失败了，你可以轻易解释和反应。例如当你尝试打开一个文件，由于文件不存在，操作失败了，你可能希望创建文件而不是终止程序。
1. `Result` 枚举有两个变体：`Ok` 和 `Err`，如下：
   ```rust
   enum Result<T, E> {
      Ok(T), 
      Err(E),
   }
   ```
   `T`， `E` 都是泛型，我们在 [[9-泛型&特性&生命周期]] 中会讲到。
2. 如果不知道返回值类型，可以查 [API](https://doc.rust-lang.org/std/index.html)，或者为返回接受的变量增加一个不可能的类型标注然后看编译错误报告。有的 编辑器 里面有提示器，鼠标放上就可以看到。
3. 类似于 `Option` 枚举，`Result` 枚举和它的变体已经在 prelude 中了，因此可以不用 `Result::` 就可以直接调用 `Ok` 和 `Err`。
4. 类似于 `Option`，对于 `Result` 类型的值，我们也不能直接使用好像它就是 `Ok` 的，而是要 `match`，我们已经讲过了。

## 匹配不同的错误
1. 可以通过在 `Err` 的分支中继续使用 `match` 来匹配 `error.kind()` 是具体 `ErrorKind` 的哪种变体来匹配不同的错误进行不同的行为。如下：
   ```rust
   use std::fs::File;
   use std::io::ErrorKind;
   fn main() {
      let f = File::open("hello.txt");
      let f = match f {
         Ok(file) => file,
         Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::creat("hello.txt") {
               Ok(fc) => fc,
               Err(e) => panic!("Problem creating the file: {:?}", e),
            }, 
            other => panic!("Problem opening the file: {:?}", other),
         }
      }
   }
   ```
1. `io::Error` 有方法 `.kind()` 来获得一个 `io::ErrorKind` 值。`io::ErrorKind` 是由 `std` 库提供，并且有不同的变体，来表示 io 操作可能发生的不同的错误。
2. ***Rust*** 中有非常多 `match`，`match` 表达式很有用，但是有点原始。`Result<T, E>` 中有很多使用了闭包的方法可以用更简洁的方式处理其中的值，如 `unwrap_or_else` 方法允许定义一些客制的、不 `panic!` 的错误处理。如果 `Result` 是一个 `Ok` 值，则此方法和 `unwrap` 类似；然而，如果是一个 `Err` 值，则调用作为参数的匿名函数 - 暨 ***闭包***。[[11-函数式编程语言特性：迭代器和闭包]] 中会具体讨论。

## 对于错误 Panic 的捷径：`unwrap` 和 `expect`
1. `match` 很不错，但是有时有点冗长，`Result<T, E>` 中有许多方法可以使用。如 `unwrap`，如果 `Result` 是 `Ok` 变体，`unwrap` 会直接返回其中的值；如果 `Result` 是 `Err` 变体，方法会直接调用 `panic!` 宏。如下：所以要么 `f` 中有合法的值，要么程序崩溃
   ```rust
   use std::fs::File;
   fn main() {
      let f = File::open("hello.txt").unwrap();
   }
   ```
2. 类似的，使用 `expect` 代替 `unwrap` 可以让我们自定义 `panic!` 宏的输出，其他功能相同，因为每个 `expect` 的输出可以是不同的，因此便于确定异常位置，**更推荐**。如下：
    ```rust
    use std::fs::File;
    fn main() {
       let f = File::open("hello.txt").expect("Failed to open hello.txt");
    }
    ```

## ***Propagating(传播)*** 异常
传播异常，通过返回 `Result<T, E>` 就可以将本应在函数中处理的异常传播出去：`fn fn_name(para) -> Result<String, io::Error>`。传播异常在 ***Rust*** 中太常见，因此提供了一个 `?` 操作符来简化。
### 传播异常捷径：`?` 操作符
1. 传播异常常规写法：
   ```rust
   use std::fs::File;
   use std::io::{self, Read};
   fn read_username_from_file() -> Result<String, io::Error> {
      let f = File::open("hello.txt");
      let mut f = match f {
         Ok(file) => file,
         Err(e) => return Err(e),
      };
      let mut s = String::new();
      match f.read_to_string(&mut s) {
         Ok(_) => Ok(s),
         Err(e) => Err(e),
      }
   }
   ```
2. 以上代码功能可以使用 `?` 简化：
   ```rust
   use std::fs::File;
   use std::io::{self, Read};
   fn read_username_from_file() -> Result<String, io::Error> {
      let mut f = File::open("hello.txt")?;
      let mut s = String::new();
      f.read_to_string(&mut s)?;
      Ok(s)
   }
   ```
3. `?` 简化，代码功能相同，除了：调用 `?` 操作符的错误值，执行了 `from` 函数，这个函数定义在标准库中的 `From` 特性中，是用来将 error 转化成另一种类型。当 `?` 调用 `from` 函数，**接收到的错误类型 被转化成了 当前函数定义的错误类型**。这十分有用，当：一个函数返回一个错误类型来标识所有此函数可能出现的错误，即使这些错误可能并不相同。只要有 `impl From<OtherError> for ReturnedError` 来定义在特性的 `from` 函数中的转化，`?` 就会自动调用 `from` 函数。代码如下：
   ```rust
   let mut f = match File::open("hello.txt") {
    Ok(file) => file,
    Err(e) => return Err(e),
   };
   ```
    简化成：`let mut f = File::open("hello.txt")?;`
4. 甚至可以链接函数调用进一步简化：
   ```rust
   fn read_username_from_file() -> Result<String, io::Error> {
      let mut s = String::new();
      File::open("hello.txt")?read_to_string(&mut s)?;
      Ok(s)
   }
   ```
5. 当然，由于以上的操作，读取一个文件，是如此常见，因此标准库里直接提供了方法：`fs::read_to_string(filename_str)` 返回 `Result<String, io::Error>`，所以可以用标准库中提供的一行代码代替我们自己写的三行。
###  `?` 操作符都在哪里能用
`?` 操作符只能使用于 **返回值**为 `Result` 或者 `Option` 或其他实现了 `FromResidual` 的类型 的函数中。如果 `?` 前是 `Error` 或者 `None`，直接返回；如果是 `Ok(val)` 或者 `Some(val)` 则其中的值为表达式结果，并且函数继续执行。
1. 注意，虽然可以对 `Result` / `Option` 值使用 `?` 操作符使函数返回 `Result` / `Option`，但是不能混用，暨 对 `Result` 使用无法自动返回 `Option` 值，反之亦然。在这些情况中，可以使用 `Result` 中的 `ok` 方法 或 `Option` 中的 `ok_or` 方法 来显式转换。
2. `main` 函数除了返回 `()` 以外，还可以返回 `Result<(), E>`，可以正常通过编译，当这样有返回值的时候，如果 `main` 函数返回 `Ok(())`，程序退出 跟随 0值 无显示；如果 `main` 返回 `Err`，则程序退出 跟随非 0 值 显示为(exit code: 1)。这点和 ***C*** 类似


# To `Panic!` or Not to `Panic!`
当代码 panic 时，没有任何办法恢复程序。你可以在任何情况下调用 `panic!`，无论是否可以恢复，但接下来你将代表调用代码决定这个情况是不可恢复的。当你返回一个 `Result` 值，你给调用代码了一个选择，它可以决定是以一种对于这个情况合适的方法来尝试恢复，还是决定这是一个在这个情况下不可恢复的 `Err` 值。因此，**返回 `Result` 是一个很好的默认选择**，当你定义一个可能失败的函数时。     

## 示例、原型代码 和 测试
当编写 **示例、原型代码和测试** 的时候，如果错误处理做的好会使代码不明晰。这种情况使用 `unwrap` 和 `expect` 方法来占位，在决定如何处理错误之前很有用，并且留下了一个清晰的**标识**以便后面 处理错误，提高软件健壮性。

## 你拥有比编译器更多的信息 的情况
如果 **100% 肯定不会出现错误值**，比如使用一些硬编码不可变的数据，直接使用 `unwrap` 也是合适的，虽然编译器本身并不理解这种逻辑。

## 错误处理的指导
当 bad state 出现时，panic 使程序中断是推荐的，暨当 一些 假设、保证、契约、不变 被打破，如 非法值、矛盾值、缺失值 被传入代码，外加以下三个条件中的至少一个：
- bad state 是 期望以外的值，与通常发生的值相悖，如用户输入了一个错误格式的数据；
- 在 bad state 之后程序需要以 非 bad state 运行，而不是每一步检查问题；
- 在使用的类型里，没有合适的方法编码这个信息；
   
1. 如果其他人使用你的库代码，或者你使用其他人的库代码，`panic!` 都是很合适的
2. 如果 **错误是意料之中的**，使用 `Result` 更合适
3. 函数通常有 ***contracts(契约)***：只有当输入满足特定要求时，才能保证它们的行为。当违反契约时 panic 是有道理的，因为违反契约总是表示 调用方 bug，而这不是你希望调用代码必须显式处理的错误。事实上，没有合理的方法 让调用代码来恢复；调用的程序员需要修复代码。应在函数的 API 文档中解释函数的约定，尤其是当违规会导致 panic 时。
4. 然而，在函数中使用很多 错误检测 是非常冗余、讨厌的，幸运的是，可以使用 ***Rust*** 的类型系统(因此，由编译器进行类型检测)。如果你的函数由一个确定类型的形参，那么 可以在已知编译器已经保证了获得一个合法值得前提下 处理代码逻辑。

## 为了验证 创建一个客制化类型
当对输入的参数有限制时，如形参类型为 `i32`，但是实际只想获得一个 0..100 的数，可以通过对实参进行条件判定来确定是否合法，但是这样代码冗长而且复用性比较差，并且可能会影响性能，这时候，我们可以创建一个新的类型，并且将验证放到它的一个方法中。如下：
```rust
pub struct Guess {
   value: i32,
}

impl Guess {
   pub fn new(value: i32) -> Guess {
      if value < 1 || value > 100 {
         panic("Guess value must be between 1 an 100, got {}.", value);
      }
      Guess {value}
   }
   
   pub fn value(&self) -> i32 {
      self.value
   }
}
```


# 代码
- *Rust/error_handle_learn/src/main.rs*